baseURL = "https://vivesimple-new.netlify.app/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Vive Simple"

###########################################################
  
[menu]
  [[menu.main]]
  name = "Home"
  url = "#home"
  weight = 1

[[menu.main]]
identifier = "aboutme"
name = "Nosotros"
url = "/acercademi"
weight = 2
    [[menu.main]]
    name = "⇾ Acerca de Mí"
    url = "/acercademi"
    parent = "aboutme"
    weight = 1
    [[menu.main]]
    name = "⇾ Nuestra historia"
    url = "/nuestrahistoria"
    parent = "aboutme"
    weight = 2

  # [[menu.main]]
  # name = "Nosotros"
  # url = "#nosotros"
  # weight = 3

  [[menu.main]]
  name = "Nuestros Servicios"
  url = "#service"
  weight = 4

  [[menu.main]]
  name = "Servicios Adicionales"
  url = "#serviciosAdicionales"
  weight = 5

  [[menu.main]]
  name = "Testimonios"
  url = "#testimonial"
  weight = 6

  [[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog"
  weight = 6
    # [[menu.main]]
    # name = "Blog1"
    # url = "/blog/1"
    # parent = "blog"
    # weight = 1
    # [[menu.main]]
    # name = "Blog2"
    # url = "/contact"
    # parent = "blog"
    # weight = 2

  [[menu.main]]
  identifier = "tienda"
  name = "Tienda"
  url = "/"
  weight = 7
    [[menu.main]]
    name = "⇾ Nuestras herramientas"
    url = "https://kit.co/vivesimple.me/vive-simple-kit-studio"
    parent = "tienda"
    weight = 1
    [[menu.main]]
    name = "⇾ Productos Digitales"
    url = "https://vivesimple.gumroad.com/"
    parent = "tienda"
    weight = 2
    [[menu.main]]
    name = "⇾ Descuento: Epidemic Sound"
    url = "https://share.epidemicsound.com/bw76ca"
    parent = "tienda"
    weight = 3

  [[menu.main]]
  name = "Contacto"
  url = "/contact"
  weight = 8
###########################################################


# Sitemap Menu
[[menu.sitemap]]
name = "Acerca de Mí"
url = "#about"
weight = 2

[[menu.sitemap]]
name = "Latest Article"
url = "/blog"
weight = 3

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Vive Simple 2023"
footerLogo = "images/site-navigation/logo.png"

# We're using formspree.io for form handling, paste your formspree url below
fabformURL  = "https://formspree.io/f/mrgwpaew"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Madrid, España"
email = "info.vivesimple@gmail.com"
# openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
# phone = "+(448) 833 5272 332"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-brands fa-youtube"
url = "https://www.youtube.com/@ViveSimple"
weight = 1

[[params.social]]
icon = "fa-instagram"
url = "https://www.instagram.com/vivesimple.me/"
weight = 2

[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/profile.php?id=100085312506276"
weight = 3

[[params.social]]
icon = "fa-solid fa-envelope"
url = "mailto:info.vivesimple@gmail.com"
weight = 4